apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: noam-bookinfo-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/NoamBrodie/devopshift-welcome.git'
    path: ./welcome/app/fe/bookinfo/manifests/manual
    targetRevision: argocd-workshop
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

  # webhook:
  #   github:
  #     secret: webhook-secret
